### PR TITLE
update Changehero plugin 

### PR DESCRIPTION
**Pull request by ruslanfirefly**
- update plugin for new api with chains

### CODE REVIEW

**Comment by paullinator** [comment]
This still doesn't work for differentiating chains. I placed a swap from ETH to MATIC both mainnet coins (not ERC20) and I received MATIC ERC20 on the ethereum address

**Review by paullinator — CHANGES_REQUESTED** [review]
This still doesn't work for differentiating chains. I placed a swap from ETH to MATIC both mainnet coins (not ERC20) and I received MATIC ERC20 on the ethereum address.

As well, for something this small, please squash into 1 commit and rebase the branch

**Comment by ruslanfirefly** [comment]
Changehero api does not support this feature for now. I think we need add this feature for next release. Because we have some problems for support new version of api for this week.

**Comment by paullinator** [comment]
Please do not merge master into your feature branch. Please start a new PR with a single commit that includes all the relevant changes.

**Pull request closed without merging**
